version: '3'
services:

  postgres:
    image: postgres:11
    ports:
      - "127.0.0.1:5434:5432"
    command: postgres -c logging_collector=on -c log_destination=stderr -c operator_precedence_warning=on -c log_directory=/var/log/postgresql -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.track=all
    environment:
      - POSTGRES_PASSWORD=pwclient1
      - POSTGRES_USER=client1
    volumes:
      - dbdata_11:/var/lib/postgresql/data
      - dblogs:/var/log/postgresql

  postgres2:
    image: postgres:12
    ports:
      - "127.0.0.1:5435:5432"
    command: postgres -c logging_collector=on -c log_destination=stderr -c operator_precedence_warning=on -c log_directory=/var/log/postgresql -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.track=all
    environment:
      - POSTGRES_PASSWORD=pwclient2
      - POSTGRES_USER=client2
    volumes:
      - dbdata_12:/var/lib/postgresql/data
      - dblogs:/var/log/postgresql

volumes:
  dbdata_11:
  dbdata_12:
  dblogs:
