version: '3'
services:

  horizontal_sharding_poc:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/Rails-Docker
      - bundle:/usr/local/bundle
      - node_modules:/usr/src/app/node_modules
    links:
      - postgres
      - postgres2
    ports:
      - '3000:3000'
    env_file:
      - .env

  postgres:
    image: postgres:11
    ports:
      - '127.0.0.1:5434:5432'
    command: postgres -c logging_collector=on -c log_destination=stderr -c operator_precedence_warning=on -c log_directory=/var/log/postgresql -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.track=all
    environment:
      - POSTGRES_PASSWORD=pwclient1
      - POSTGRES_USER=client1
    volumes:
      - dbdata_11:/var/lib/postgresql/data
      - dblogs:/var/log/postgresql

  postgres2:
    image: postgres:12
    ports:
      - '127.0.0.1:5435:5432'
    command: postgres -c logging_collector=on -c log_destination=stderr -c operator_precedence_warning=on -c log_directory=/var/log/postgresql -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.track=all
    environment:
      - POSTGRES_PASSWORD=pwclient2
      - POSTGRES_USER=client2
    volumes:
      - dbdata_12:/var/lib/postgresql/data
      - dblogs:/var/log/postgresql

  webpack:
    build: .
    image: rails-on-docker:1.5.0
    command: yarn build --watch
    volumes:
      - .:/usr/src/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/usr/src/app/node_modules

volumes:
  dbdata_11:
  dbdata_12:
  dblogs:
  node_modules:
  bundle: